### ISSUE TITLE
Package is invalid. Details: 'Could not load icon 'images/trello_it_logo.png' for browser action.'.

### ISSUE THREAD

**Issue by cben** [wyegelwel/Trello_It#6]
Error trying to install from Chrome Web Store, using Chromium Version 43.0.2357.130 Ubuntu 15.04 (64-bit):
![add it for trello - chrome web store](https://cloud.githubusercontent.com/assets/273688/8846124/3ce9ac88-312d-11e5-832c-9f0aad98ef89.png)

I see there exists `images/Trello_it_logo.png` with capital T — so I guess it's a simple case mismatch, unnoticed before because it doesn't matter on Windows?

**Comment by wyegelwel** [comment]
Almost certainly the case. I'm out of town for the weekend, I will try to
fix it early next week. Thanks for the heads up!

**Comment by wyegelwel** [comment]
This should be fixed now. Thanks for the issue, let me know if you run into anything else.

**Comment by cben** [comment]
Indeed, 0.3 installed with no problem from Chrome Store, works.
